title: Story Engine
description: A discord interactions service that provides a platform for interactive stories written by the community.

discord_url: https://discord.gg/Bb3JQQG

collections:
  goals:
    layout: goal
    output:
      permalink: /roadmap/:title/
  guides:
    output:
      permalink: /guides/:title/
    sort_by: date

defaults:
  - scope:
      path: ./guides/
    values:
      layout: guide
  - scope:
      path: .
    values:
      layout: default