title: Story Engine
description: A discord interactions service that provides a platform for interactive stories written by the community.

discord_url: https://discord.gg/Bb3JQQG

collections_dir: ./collections

collections:
  goals:
    output: false
    sort: priority
  guides:
    output:
      permalink: /:title/
    sort: date

defaults:
  - scope:
      path: ./guides/
    values:
      layout: guide
  - scope:
      path: .
    values:
      layout: default